import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/appSidebar";


import MyMantineProvider from "@/components/mantine-provider";
import '@mantine/charts/styles.css';
import '@mantine/core/styles.css';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="">
      <body>
        <MyMantineProvider>
        <SidebarProvider>
          <AppSidebar />
       

          <main className=" w-full bg-slate-100 dark:bg-gray-500  ">

            <div className="h-20  flex items-center p-4 bg-white shadow dark:bg-gray-900">

            <SidebarTrigger/>
            </div>
       
            {children}
            
            </main>





        
        </SidebarProvider>

        <footer className="bg-gray-300">
  <div className="mx-auto max-w-screen-xl px-4 py-8 sm:px-6 lg:px-8">
    <div className="sm:flex sm:items-center sm:justify-between">
      <div className="flex justify-center text-teal-600 sm:justify-start">
       Admin Template::
      </div>

      <p className="mt-4 text-center text-sm text-gray-500 lg:mt-0 lg:text-right">
        Copyright &copy; 2022. All rights reserved.
      </p>
    </div>
  </div>
</footer>

        </MyMantineProvider>

      </body>
    </html>
  );
}